apiVersion: apps/v1
kind: Deployment
metadata:
  name: storm-$nodeName-$tagName
  labels:
    app: storm-$nodeName-$tagName
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storm-$nodeName-$tagName  
  template:
    metadata:
      labels:
        app: storm-$nodeName-$tagName
    spec:
      containers:
      - name: storm-$nodeName-$tagName
        image: kevin2333/storm-worker:latest
        env:
          - name: TAG_NAME
            value: "storm-$nodeName-$tagName"
          - name: SLOT_NUM 
            value: "$slotNum"
        ports:
          - name: w6700
            containerPort: 6700
          - name: w6701
            containerPort: 6701
